/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as GetHelpRouteImport } from './routes/get-help'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesPsychosocialSupportRouteImport } from './routes/programmes.psychosocial-support'
import { Route as ProgrammesMensEngagementRouteImport } from './routes/programmes.mens-engagement'
import { Route as ProgrammesHumanRightsClubsRouteImport } from './routes/programmes.human-rights-clubs'
import { Route as ProgrammesFirstRespondersRouteImport } from './routes/programmes.first-responders'
import { Route as ProgrammesCommunityKitchenRouteImport } from './routes/programmes.community-kitchen'
import { Route as ProgrammesBbbBoysRouteImport } from './routes/programmes.bbb-boys'
import { Route as ProgrammesAccessToJusticeRouteImport } from './routes/programmes.access-to-justice'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const GetHelpRoute = GetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesPsychosocialSupportRoute =
  ProgrammesPsychosocialSupportRouteImport.update({
    id: '/psychosocial-support',
    path: '/psychosocial-support',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesMensEngagementRoute =
  ProgrammesMensEngagementRouteImport.update({
    id: '/mens-engagement',
    path: '/mens-engagement',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesHumanRightsClubsRoute =
  ProgrammesHumanRightsClubsRouteImport.update({
    id: '/human-rights-clubs',
    path: '/human-rights-clubs',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesFirstRespondersRoute =
  ProgrammesFirstRespondersRouteImport.update({
    id: '/first-responders',
    path: '/first-responders',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesCommunityKitchenRoute =
  ProgrammesCommunityKitchenRouteImport.update({
    id: '/community-kitchen',
    path: '/community-kitchen',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesBbbBoysRoute = ProgrammesBbbBoysRouteImport.update({
  id: '/bbb-boys',
  path: '/bbb-boys',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesAccessToJusticeRoute =
  ProgrammesAccessToJusticeRouteImport.update({
    id: '/access-to-justice',
    path: '/access-to-justice',
    getParentRoute: () => ProgrammesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/get-help': typeof GetHelpRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/support': typeof SupportRoute
  '/volunteer': typeof VolunteerRoute
  '/programmes/access-to-justice': typeof ProgrammesAccessToJusticeRoute
  '/programmes/bbb-boys': typeof ProgrammesBbbBoysRoute
  '/programmes/community-kitchen': typeof ProgrammesCommunityKitchenRoute
  '/programmes/first-responders': typeof ProgrammesFirstRespondersRoute
  '/programmes/human-rights-clubs': typeof ProgrammesHumanRightsClubsRoute
  '/programmes/mens-engagement': typeof ProgrammesMensEngagementRoute
  '/programmes/psychosocial-support': typeof ProgrammesPsychosocialSupportRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/get-help': typeof GetHelpRoute
  '/support': typeof SupportRoute
  '/volunteer': typeof VolunteerRoute
  '/programmes/access-to-justice': typeof ProgrammesAccessToJusticeRoute
  '/programmes/bbb-boys': typeof ProgrammesBbbBoysRoute
  '/programmes/community-kitchen': typeof ProgrammesCommunityKitchenRoute
  '/programmes/first-responders': typeof ProgrammesFirstRespondersRoute
  '/programmes/human-rights-clubs': typeof ProgrammesHumanRightsClubsRoute
  '/programmes/mens-engagement': typeof ProgrammesMensEngagementRoute
  '/programmes/psychosocial-support': typeof ProgrammesPsychosocialSupportRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/get-help': typeof GetHelpRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/support': typeof SupportRoute
  '/volunteer': typeof VolunteerRoute
  '/programmes/access-to-justice': typeof ProgrammesAccessToJusticeRoute
  '/programmes/bbb-boys': typeof ProgrammesBbbBoysRoute
  '/programmes/community-kitchen': typeof ProgrammesCommunityKitchenRoute
  '/programmes/first-responders': typeof ProgrammesFirstRespondersRoute
  '/programmes/human-rights-clubs': typeof ProgrammesHumanRightsClubsRoute
  '/programmes/mens-engagement': typeof ProgrammesMensEngagementRoute
  '/programmes/psychosocial-support': typeof ProgrammesPsychosocialSupportRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/get-help'
    | '/programmes'
    | '/support'
    | '/volunteer'
    | '/programmes/access-to-justice'
    | '/programmes/bbb-boys'
    | '/programmes/community-kitchen'
    | '/programmes/first-responders'
    | '/programmes/human-rights-clubs'
    | '/programmes/mens-engagement'
    | '/programmes/psychosocial-support'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/get-help'
    | '/support'
    | '/volunteer'
    | '/programmes/access-to-justice'
    | '/programmes/bbb-boys'
    | '/programmes/community-kitchen'
    | '/programmes/first-responders'
    | '/programmes/human-rights-clubs'
    | '/programmes/mens-engagement'
    | '/programmes/psychosocial-support'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/get-help'
    | '/programmes'
    | '/support'
    | '/volunteer'
    | '/programmes/access-to-justice'
    | '/programmes/bbb-boys'
    | '/programmes/community-kitchen'
    | '/programmes/first-responders'
    | '/programmes/human-rights-clubs'
    | '/programmes/mens-engagement'
    | '/programmes/psychosocial-support'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  GetHelpRoute: typeof GetHelpRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  SupportRoute: typeof SupportRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-help': {
      id: '/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof GetHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/psychosocial-support': {
      id: '/programmes/psychosocial-support'
      path: '/psychosocial-support'
      fullPath: '/programmes/psychosocial-support'
      preLoaderRoute: typeof ProgrammesPsychosocialSupportRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/mens-engagement': {
      id: '/programmes/mens-engagement'
      path: '/mens-engagement'
      fullPath: '/programmes/mens-engagement'
      preLoaderRoute: typeof ProgrammesMensEngagementRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/human-rights-clubs': {
      id: '/programmes/human-rights-clubs'
      path: '/human-rights-clubs'
      fullPath: '/programmes/human-rights-clubs'
      preLoaderRoute: typeof ProgrammesHumanRightsClubsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/first-responders': {
      id: '/programmes/first-responders'
      path: '/first-responders'
      fullPath: '/programmes/first-responders'
      preLoaderRoute: typeof ProgrammesFirstRespondersRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/community-kitchen': {
      id: '/programmes/community-kitchen'
      path: '/community-kitchen'
      fullPath: '/programmes/community-kitchen'
      preLoaderRoute: typeof ProgrammesCommunityKitchenRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/bbb-boys': {
      id: '/programmes/bbb-boys'
      path: '/bbb-boys'
      fullPath: '/programmes/bbb-boys'
      preLoaderRoute: typeof ProgrammesBbbBoysRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/access-to-justice': {
      id: '/programmes/access-to-justice'
      path: '/access-to-justice'
      fullPath: '/programmes/access-to-justice'
      preLoaderRoute: typeof ProgrammesAccessToJusticeRouteImport
      parentRoute: typeof ProgrammesRoute
    }
  }
}

interface ProgrammesRouteChildren {
  ProgrammesAccessToJusticeRoute: typeof ProgrammesAccessToJusticeRoute
  ProgrammesBbbBoysRoute: typeof ProgrammesBbbBoysRoute
  ProgrammesCommunityKitchenRoute: typeof ProgrammesCommunityKitchenRoute
  ProgrammesFirstRespondersRoute: typeof ProgrammesFirstRespondersRoute
  ProgrammesHumanRightsClubsRoute: typeof ProgrammesHumanRightsClubsRoute
  ProgrammesMensEngagementRoute: typeof ProgrammesMensEngagementRoute
  ProgrammesPsychosocialSupportRoute: typeof ProgrammesPsychosocialSupportRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesAccessToJusticeRoute: ProgrammesAccessToJusticeRoute,
  ProgrammesBbbBoysRoute: ProgrammesBbbBoysRoute,
  ProgrammesCommunityKitchenRoute: ProgrammesCommunityKitchenRoute,
  ProgrammesFirstRespondersRoute: ProgrammesFirstRespondersRoute,
  ProgrammesHumanRightsClubsRoute: ProgrammesHumanRightsClubsRoute,
  ProgrammesMensEngagementRoute: ProgrammesMensEngagementRoute,
  ProgrammesPsychosocialSupportRoute: ProgrammesPsychosocialSupportRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  GetHelpRoute: GetHelpRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  SupportRoute: SupportRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
