/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminImpactRouteImport } from './routes/admin.impact'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as PublicVolunteerRouteImport } from './routes/_public.volunteer'
import { Route as PublicSupportOurWorkRouteImport } from './routes/_public.support-our-work'
import { Route as PublicShopRouteImport } from './routes/_public.shop'
import { Route as PublicResourcesRouteImport } from './routes/_public.resources'
import { Route as PublicProgrammesRouteImport } from './routes/_public.programmes'
import { Route as PublicPartnersRouteImport } from './routes/_public.partners'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicGetHelpRouteImport } from './routes/_public.get-help'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicFounderRouteImport } from './routes/_public.founder'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicDonateRouteImport } from './routes/_public.donate'
import { Route as PublicCookiesRouteImport } from './routes/_public.cookies'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicProgrammesIndexRouteImport } from './routes/_public.programmes.index'
import { Route as PublicNewsIndexRouteImport } from './routes/_public.news.index'
import { Route as PublicProgrammesSlugRouteImport } from './routes/_public.programmes.$slug'
import { Route as PublicNewsSlugRouteImport } from './routes/_public.news.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVolunteerRoute = PublicVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSupportOurWorkRoute = PublicSupportOurWorkRouteImport.update({
  id: '/support-our-work',
  path: '/support-our-work',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShopRoute = PublicShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProgrammesRoute = PublicProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartnersRoute = PublicPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGetHelpRoute = PublicGetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFounderRoute = PublicFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDonateRoute = PublicDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProgrammesIndexRoute = PublicProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProgrammesRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicProgrammesSlugRoute = PublicProgrammesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicProgrammesRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/donate': typeof PublicDonateRoute
  '/events': typeof PublicEventsRoute
  '/founder': typeof PublicFounderRoute
  '/gallery': typeof PublicGalleryRoute
  '/get-help': typeof PublicGetHelpRoute
  '/news': typeof PublicNewsRouteWithChildren
  '/partners': typeof PublicPartnersRoute
  '/programmes': typeof PublicProgrammesRouteWithChildren
  '/resources': typeof PublicResourcesRoute
  '/shop': typeof PublicShopRoute
  '/support-our-work': typeof PublicSupportOurWorkRoute
  '/volunteer': typeof PublicVolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/programmes/$slug': typeof PublicProgrammesSlugRoute
  '/news/': typeof PublicNewsIndexRoute
  '/programmes/': typeof PublicProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/donate': typeof PublicDonateRoute
  '/events': typeof PublicEventsRoute
  '/founder': typeof PublicFounderRoute
  '/gallery': typeof PublicGalleryRoute
  '/get-help': typeof PublicGetHelpRoute
  '/partners': typeof PublicPartnersRoute
  '/resources': typeof PublicResourcesRoute
  '/shop': typeof PublicShopRoute
  '/support-our-work': typeof PublicSupportOurWorkRoute
  '/volunteer': typeof PublicVolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/programmes/$slug': typeof PublicProgrammesSlugRoute
  '/news': typeof PublicNewsIndexRoute
  '/programmes': typeof PublicProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/donate': typeof PublicDonateRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/founder': typeof PublicFounderRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/get-help': typeof PublicGetHelpRoute
  '/_public/news': typeof PublicNewsRouteWithChildren
  '/_public/partners': typeof PublicPartnersRoute
  '/_public/programmes': typeof PublicProgrammesRouteWithChildren
  '/_public/resources': typeof PublicResourcesRoute
  '/_public/shop': typeof PublicShopRoute
  '/_public/support-our-work': typeof PublicSupportOurWorkRoute
  '/_public/volunteer': typeof PublicVolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/_public/programmes/$slug': typeof PublicProgrammesSlugRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_public/programmes/': typeof PublicProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/get-help'
    | '/news'
    | '/partners'
    | '/programmes'
    | '/resources'
    | '/shop'
    | '/support-our-work'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/messages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/'
    | '/news/$slug'
    | '/programmes/$slug'
    | '/news/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/cookies'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/get-help'
    | '/partners'
    | '/resources'
    | '/shop'
    | '/support-our-work'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/messages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/team'
    | '/'
    | '/admin'
    | '/news/$slug'
    | '/programmes/$slug'
    | '/news'
    | '/programmes'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/cookies'
    | '/_public/donate'
    | '/_public/events'
    | '/_public/founder'
    | '/_public/gallery'
    | '/_public/get-help'
    | '/_public/news'
    | '/_public/partners'
    | '/_public/programmes'
    | '/_public/resources'
    | '/_public/shop'
    | '/_public/support-our-work'
    | '/_public/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/messages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/team'
    | '/_public/'
    | '/admin/'
    | '/_public/news/$slug'
    | '/_public/programmes/$slug'
    | '/_public/news/'
    | '/_public/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact': {
      id: '/admin/impact'
      path: '/impact'
      fullPath: '/admin/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/volunteer': {
      id: '/_public/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof PublicVolunteerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/support-our-work': {
      id: '/_public/support-our-work'
      path: '/support-our-work'
      fullPath: '/support-our-work'
      preLoaderRoute: typeof PublicSupportOurWorkRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shop': {
      id: '/_public/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof PublicShopRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programmes': {
      id: '/_public/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof PublicProgrammesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/partners': {
      id: '/_public/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PublicPartnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/get-help': {
      id: '/_public/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof PublicGetHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/founder': {
      id: '/_public/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof PublicFounderRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/donate': {
      id: '/_public/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof PublicDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programmes/': {
      id: '/_public/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof PublicProgrammesIndexRouteImport
      parentRoute: typeof PublicProgrammesRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/programmes/$slug': {
      id: '/_public/programmes/$slug'
      path: '/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof PublicProgrammesSlugRouteImport
      parentRoute: typeof PublicProgrammesRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicNewsRoute
    }
  }
}

interface PublicNewsRouteChildren {
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
}

const PublicNewsRouteChildren: PublicNewsRouteChildren = {
  PublicNewsSlugRoute: PublicNewsSlugRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
}

const PublicNewsRouteWithChildren = PublicNewsRoute._addFileChildren(
  PublicNewsRouteChildren,
)

interface PublicProgrammesRouteChildren {
  PublicProgrammesSlugRoute: typeof PublicProgrammesSlugRoute
  PublicProgrammesIndexRoute: typeof PublicProgrammesIndexRoute
}

const PublicProgrammesRouteChildren: PublicProgrammesRouteChildren = {
  PublicProgrammesSlugRoute: PublicProgrammesSlugRoute,
  PublicProgrammesIndexRoute: PublicProgrammesIndexRoute,
}

const PublicProgrammesRouteWithChildren =
  PublicProgrammesRoute._addFileChildren(PublicProgrammesRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicDonateRoute: typeof PublicDonateRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicFounderRoute: typeof PublicFounderRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicGetHelpRoute: typeof PublicGetHelpRoute
  PublicNewsRoute: typeof PublicNewsRouteWithChildren
  PublicPartnersRoute: typeof PublicPartnersRoute
  PublicProgrammesRoute: typeof PublicProgrammesRouteWithChildren
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicShopRoute: typeof PublicShopRoute
  PublicSupportOurWorkRoute: typeof PublicSupportOurWorkRoute
  PublicVolunteerRoute: typeof PublicVolunteerRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicDonateRoute: PublicDonateRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicFounderRoute: PublicFounderRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicGetHelpRoute: PublicGetHelpRoute,
  PublicNewsRoute: PublicNewsRouteWithChildren,
  PublicPartnersRoute: PublicPartnersRoute,
  PublicProgrammesRoute: PublicProgrammesRouteWithChildren,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicShopRoute: PublicShopRoute,
  PublicSupportOurWorkRoute: PublicSupportOurWorkRoute,
  PublicVolunteerRoute: PublicVolunteerRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
